# Generated by Django 4.0.6 on 2022-07-23 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=30)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Liter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liters', to='api.complex')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('liter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.liter')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('area', models.FloatField()),
                ('plan', models.URLField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('d', models.CharField(max_length=800)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='api.plan')),
            ],
        ),
        migrations.AddField(
            model_name='floor',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.plan'),
        ),
        migrations.AddField(
            model_name='floor',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='api.section'),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city')),
            ],
        ),
        migrations.AddField(
            model_name='complex',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexes', to='api.district'),
        ),
        migrations.CreateModel(
            name='CommercialRecommendationsRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welfare_score', models.FloatField()),
                ('traffic_score', models.FloatField()),
                ('competitors_score', models.FloatField()),
                ('population_score', models.FloatField()),
                ('sector', models.CharField(max_length=255, null=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_recommendations', to='api.commercial')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.complex')),
            ],
        ),
        migrations.CreateModel(
            name='ClientRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Продано', 'Продано'), ('Арендуется', 'Арендуется')], max_length=150)),
                ('price_per_month', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_rooms', to='api.client')),
                ('commercial_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.commercial')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_room', to='api.room')),
            ],
        ),
    ]
